[package]
name = "rimuy/gamejoy"
description = "A simple class-based input library"
version = "1.1.0"
license = "MIT"
authors = ["Rimuy"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["*.d.ts"]

[dependencies]